<?php

namespace App\Console\Commands;

use App\Models\ProductVariant;
use App\Services\ActivityLogService;
use Illuminate\Console\Command;

/**
 * One-off: rename existing variants to the colour-led merchandising scheme
 * (ProductVariant::composeName) — "Black / black / Purple Red" becomes
 * "White Princes Cassock + Black Piping, Buttons and Pleats".
 *
 * Safe by default and re-runnable:
 *   - Only renames variants whose CURRENT name is clearly auto-generated
 *     (the legacy "value / value / value" join of their own attributes, or an
 *     empty name). Hand-edited names are left alone unless --all is passed.
 *   - --dry-run prints every change without writing.
 *   - --product=ID scopes to one product.
 *   - Prints an old→new mapping and logs each rename to the activity trail,
 *     so the change is auditable and reversible.
 *
 *   php artisan variants:recompose-names --dry-run
 *   php artisan variants:recompose-names
 *   php artisan variants:recompose-names --all --product=90
 */
class RecomposeVariantNames extends Command
{
    protected $signature = 'variants:recompose-names
                            {--dry-run   : Print changes without writing.}
                            {--all       : Rename every variant, even hand-edited names.}
                            {--product=  : Limit to one product id.}';

    protected $description = 'Rename existing variants to the colour-led naming scheme';

    public function handle(): int
    {
        $dry = (bool) $this->option('dry-run');

        $variants = ProductVariant::with('product.translations')
            ->when($this->option('product'), fn ($q) => $q->where('product_id', (int) $this->option('product')))
            ->get();

        $renamed = 0;
        $skipped = 0;
        $rows    = [];

        foreach ($variants as $variant) {
            $attrs = $variant->attributes ?? [];
            $productName = $variant->product?->translations->firstWhere('language_code', 'en')?->name
                ?? $variant->product?->translations->first()?->name
                ?? $variant->product?->sku
                ?? '';

            $new = ProductVariant::composeName($productName, $attrs);
            $old = (string) $variant->variant_name;

            if ($new === '' || $new === $old) {
                continue;
            }

            // Only touch names that are clearly auto-generated, unless --all.
            if (!$this->option('all') && !$this->looksAutoGenerated($old, $attrs)) {
                $skipped++;
                continue;
            }

            $rows[] = [$variant->id, $variant->sku, $old ?: '—', $new];

            if (!$dry) {
                $variant->update(['variant_name' => $new]);
                try {
                    ActivityLogService::log('product_variant_renamed', $variant->product, [
                        'variant_id' => $variant->id,
                        'sku'        => $variant->sku,
                        'from'       => $old,
                        'to'         => $new,
                    ]);
                } catch (\Exception) {}
            }
            $renamed++;
        }

        if ($rows) {
            $this->table(['ID', 'SKU', 'Old name', 'New name'], $rows);
        }

        $verb = $dry ? 'Would rename' : 'Renamed';
        $this->info("{$verb} {$renamed} variant(s)." . ($skipped ? " Skipped {$skipped} hand-edited name(s) (use --all to include)." : ''));
        if ($dry && $renamed) {
            $this->comment('Dry run — nothing written. Re-run without --dry-run to apply.');
        }

        return self::SUCCESS;
    }

    /**
     * The pre-migration generator named variants by joining their attribute
     * values with " / " ("Black / black / Purple Red"). A name that still
     * matches that join — or is empty — was never hand-edited, so it is safe
     * to recompose. Any other string is treated as intentional.
     */
    private function looksAutoGenerated(string $name, array $attrs): bool
    {
        if (trim($name) === '') {
            return true;
        }
        $legacy = implode(' / ', array_map(fn ($v) => (string) $v, array_values($attrs)));
        return $name === $legacy;
    }
}
